// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nrbcTestTask.Models;

#nullable disable

namespace nrbcTestTask.Migrations
{
	[DbContext(typeof(ApplicationDBContext))]
	[Migration("20230519070500_Initial")]
	partial class Initial
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("ProductVersion", "6.0.16")
					.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b => {
				b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

				SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

				b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

				b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

				b.Property<Guid>("UserId")
						.HasColumnType("uniqueidentifier");

				b.HasKey("Id");

				b.HasIndex("UserId");

				b.ToTable("UserClaims", (string)null);
			});

			modelBuilder.Entity("nrbcTestTask.Models.ApplicationUser", b => {
				b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

				b.Property<string>("ConcurrencyStamp")
						.HasColumnType("nvarchar(max)");

				b.Property<string>("NormalizedUserName")
						.HasMaxLength(128)
						.HasColumnType("nvarchar(128)");

				b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

				b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

				b.Property<string>("UserName")
						.HasMaxLength(128)
						.HasColumnType("nvarchar(128)");

				b.HasKey("Id");

				b.ToTable("Users", (string)null);
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b => {
				b.HasOne("nrbcTestTask.Models.ApplicationUser", null)
						.WithMany("Claims")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
			});

			modelBuilder.Entity("nrbcTestTask.Models.ApplicationUser", b => {
				b.Navigation("Claims");
			});
#pragma warning restore 612, 618
		}
	}
}
